### ISSUE TITLE
Unable to get API key on PSD2-API sandbox

### ISSUE THREAD

**Issue by tuyen-vuduc** [OpenBankProject/OBP-iOS-Starter#1]
Unable to register a new application at PSD2 API sandbox site
http://psd2-api.openbankproject.com/

Any advices?

**Comment by t0rst** [comment]
There is a fix in that area already in the pipeline but not yet sure when it will be deployed on http://psd2-api.openbankproject.com/ - should be soon. In the mean time, you can try out with http://apisandbox.openbankproject.com/.

Important: when you register a new iOS app as an API consumer, you need to form the callback url like this `x-${PRODUCT_BUNDLE_IDENTIFIER:lower}://callback` hence if your app bundle id is `com.kanvuduc.myapp`, then your callback url needs to be `x-com.kanvuduc.myapp://callback`. 

Also: be sure to save a copy of your registration confirmation page as a PDF - you will need the consumer ID if you later change your app bundle id and then need to update your registered callback URL.

(The current version of http://psd2-api.openbankproject.com/ will reject this form of URL, but it will be accepted after next redeploy.)

**Comment by simonredfern** [comment]
We need to run a DB migration on this sandbox. @kanvuduc In the mean time please could you use https://apisandbox.openbankproject.com/ ? And use the PSD2 catalog there?

**Comment by tuyen-vuduc** [comment]
Thank you both. Let me try then.

**Comment by moule3053** [comment]
@kanvuduc The database migration has been done. Could you try now?

**Comment by tuyen-vuduc** [comment]
It works. Thank you, guys! Great job!
